FROM php:8.2-fpm

ENV TZ Asia/Tokyo

RUN apt-get update && \
	apt-get install -y git unzip libzip-dev libicu-dev libonig-dev

# install php extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath zip gd mysqli
RUN docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/user/include
RUN docker-php-ext-install -j$(nproc) gd
 
# set working directory
	
COPY ./docker/php/php.ini /usr/local/etc/php/php.ini

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html